# Generated by Django 3.0 on 2021-03-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empleado', '0002_farmacia'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='id_farmacia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empleado.Farmacia'),
            preserve_default=False,
        ),
    ]
