# Generated by Django 3.0 on 2021-03-19 22:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('no_cheque', models.CharField(max_length=200)),
                ('estado_che', models.BooleanField(default=False)),
                ('cantidad', models.FloatField(default=0)),
                ('fecha_pagar', models.DateField(blank=True)),
                ('fecha_creado', models.DateField(default=datetime.date.today, verbose_name='feche creado')),
                ('no_fac', models.CharField(max_length=20)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cheques/')),
                ('status', models.CharField(blank=True, choices=[('R', 'R'), ('E', 'E')], max_length=1, null=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Cuenta')),
            ],
            options={
                'verbose_name_plural': 'Cheques',
            },
        ),
        migrations.CreateModel(
            name='Fisico_Entregado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre al que se le entrego')),
                ('fecha_creado', models.DateField(auto_now_add=True)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Cheque')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque entregado',
                'verbose_name_plural': 'Cheques entregados',
                'db_table': 'Che_Fisico',
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('no_fac', models.CharField(max_length=25, unique=True, verbose_name='Factura')),
                ('total_fac', models.FloatField(default=0)),
                ('estado_fac', models.NullBooleanField(default=0)),
                ('fecha_pagar', models.DateField(blank=True)),
                ('imagen_fac', models.ImageField(blank=True, null=True, upload_to='factura/')),
                ('total_fac1', models.FloatField(default=0)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Provedor')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'db_table': 'Factura',
            },
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('no_depo', models.CharField(max_length=50)),
                ('cantidad', models.FloatField(default=0)),
                ('fecha_creado', models.DateField(default=datetime.date.today, verbose_name='feche creado')),
                ('imagen_dep', models.ImageField(blank=True, null=True, upload_to='deposito/')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Cheque')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Depositos',
            },
        ),
        migrations.CreateModel(
            name='Cheque_rechazado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('observacion', models.CharField(max_length=200, verbose_name='Observacion')),
                ('cheque_nu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='che_cheque_rechazado_nu', to='che.Cheque')),
                ('cheque_re', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Cheque')),
                ('id_facturas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Factura')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque rechazado',
                'verbose_name_plural': 'Cheques rechazados',
                'db_table': 'Che_rechazado',
            },
        ),
        migrations.AddField(
            model_name='cheque',
            name='id_fac',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Factura'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro.Provedor'),
        ),
        migrations.AddField(
            model_name='cheque',
            name='uc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Abono_Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('estado_abono', models.BooleanField(default=True)),
                ('total', models.FloatField(default=0)),
                ('id_cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Cheque')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Factura')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abono_Factura',
                'verbose_name_plural': 'Abonos de Facturas',
                'db_table': 'Abono_factura',
            },
        ),
    ]
