# Generated by Django 3.0 on 2019-12-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='fecha_creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cheque',
            name='imagen',
            field=models.ImageField(default=1, upload_to='cheques/'),
            preserve_default=False,
        ),
    ]
