# Generated by Django 3.0 on 2021-03-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(blank=True, choices=[('E', 'E')], max_length=1, null=True),
        ),
    ]
