# Generated by Django 3.0 on 2020-01-03 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0002_auto_20191224_0901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='fecha_creado',
            field=models.DateField(),
        ),
    ]
