# Generated by Django 3.0 on 2020-01-18 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0002_auto_20200117_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='estado_che',
            field=models.BooleanField(default=True),
        ),
    ]
