# Generated by Django 3.0 on 2020-01-30 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0004_auto_20200118_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='fecha_creado',
            field=models.DateField(default=datetime.date.today, verbose_name='feche creado'),
        ),
    ]
