# Generated by Django 3.0 on 2021-07-05 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0004_auto_20210705_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='total_fac',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='factura',
            name='total_fac1',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=9),
        ),
    ]
