# Generated by Django 3.0 on 2020-03-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0005_auto_20200129_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='status',
            field=models.CharField(blank=True, choices=[('r', 'rechazado'), ('e', 'erro de escritura')], max_length=1, null=True),
        ),
    ]
