# Generated by Django 3.0 on 2021-08-19 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0005_auto_20210705_0914'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_recibo', models.CharField(max_length=30)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('monto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('factura', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='che.Factura')),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'recibo',
            },
        ),
    ]
