# Generated by Django 3.0 on 2020-07-14 14:50

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('che', '0006_cheque_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='status',
            field=models.CharField(blank=True, choices=[('R', 'R'), ('E', 'E')], max_length=1, null=True),
        ),
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('no_depo', models.CharField(max_length=50)),
                ('cantidad', models.FloatField(default=0)),
                ('fecha_creado', models.DateField(default=datetime.date.today, verbose_name='feche creado')),
                ('imagen_dep', models.ImageField(blank=True, null=True, upload_to='deposito/')),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Cheque')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Depositos',
            },
        ),
    ]
