# Generated by Django 3.0 on 2021-08-19 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0006_recibo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abono_factura',
            name='id_cheque',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='che.Cheque'),
        ),
    ]
