# Generated by Django 3.0 on 2020-11-17 21:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('che', '0007_auto_20200714_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fisico_Entregado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre al que se le entrego')),
                ('fecha_creado', models.DateField(auto_now_add=True)),
                ('cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Cheque')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque entregado',
                'verbose_name_plural': 'Cheques entregados',
                'db_table': 'Che_Fisico',
            },
        ),
    ]
