# Generated by Django 3.0 on 2021-08-20 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0007_auto_20210819_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='abono_factura',
            name='recibo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='che.Recibo'),
        ),
    ]
