# Generated by Django 3.0 on 2020-11-19 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('che', '0008_fisico_entregado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cheque_rechazado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('observacion', models.CharField(max_length=200, verbose_name='Observacion')),
                ('cheque_nu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='che_cheque_rechazado_nu', to='che.Cheque')),
                ('cheque_re', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='che_cheque_rechazado_re', to='che.Cheque')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cheque rechazado',
                'verbose_name_plural': 'Cheques rechazados',
                'db_table': 'Che_rechazado',
            },
        ),
    ]
