# Generated by Django 3.0 on 2021-03-13 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('che', '0010_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abono_Factura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.BooleanField(default=True)),
                ('fc', models.DateTimeField(auto_now_add=True)),
                ('fm', models.DateTimeField(auto_now_add=True)),
                ('um', models.IntegerField(blank=True, null=True)),
                ('estado_abono', models.BooleanField(default=True)),
                ('id_cheque', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Cheque')),
                ('id_factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='che.Factura')),
                ('uc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abono_Factura',
                'verbose_name_plural': 'Abonos de Facturas',
                'db_table': 'Abono_factura',
            },
        ),
    ]
