# Generated by Django 3.0 on 2021-03-15 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0012_abono_factura_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='total_fac1',
            field=models.FloatField(default=0),
        ),
    ]
