# Generated by Django 3.0 on 2021-03-17 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('che', '0013_factura_total_fac1'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='id_fac',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='che.Factura'),
            preserve_default=False,
        ),
    ]
