# Generated by Django 3.0 on 2021-08-19 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banco',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
